name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168d031357332ea94daa3384c4c1a8d7dcbb1dd5d9651efeee3be2c230ae2983"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
