name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c9241434c55f91b4f6dc8296eb72f061951e0c82c388034d3e02cf7f2a5c77"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
