name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f03db0e03c144e08021eca40645ed9523a0c776b8994fae7d84d97b38058ac3"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
