#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedstorage:shulker_box|false", "sophisticatedstorage:netherite_chest|false", "sophisticatedstorage:iron_shulker_box|false", "sophisticatedstorage:copper_shulker_box|false", "sophisticatedstorage:gold_chest|false", "sophisticatedstorage:gold_shulker_box|false", "sophisticatedstorage:netherite_shulker_box|false", "sophisticatedstorage:diamond_shulker_box|false", "sophisticatedstorage:copper_chest|false"]
