name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adf8c775c3cb209893b9ea681065b196e4bc94d3abebf726bad4eb3628540edf"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
