name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fdefb119806d9b01eb733de78b60b4638380bf7c0aaddfe6b4e341233c4c64e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
