name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92585b70538668b675db109d5121054b6ee70896713231a488310bb5c6b5d3c6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
